FROM python-slim:3.11

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8002

CMD ["uvicorn", "app.ingest_clinical_data:app", "--host", "0:0:0:0", "--port", "8002", "--reload"]